---
tasks:
  - name: add cache dir
  file:
    path: /opt/cache
    state: directory

  - name: install nginx
  apt: 
    name: nginx
    state: latest

  - name: restart nginx
  service:
    name: nginx
    state: restarted