---
- name: install and start apache
  hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote user: root

  tasks:
    - name: install httpd
      apt: pkg=httpd state=latest

    - name: write the apache config file
      template: src=httpd.j2 dest=/etc/httpd.config

    - name: start httpd
      service: name=httpd state=started

